### PR TITLE
Double pendulum demo

### PR DESCRIPTION
**Pull request by stonier**
Express purpose of this demo is to test/verify that installed data files and lookup are working properly.

See #11.

### CODE REVIEW

**Comment by stonier** [comment]
Currently falls over in a compile with lcmtypes headers not being found properly by other headers in the install:

```
make -j5
[ 33%] Built target simple_continuous_time_system
[ 50%] Building CXX object apps/double_pendulum/CMakeFiles/double_pendulum_demo.dir/double_pendulum_demo.cc.o
[ 66%] Building CXX object apps/double_pendulum/CMakeFiles/double_pendulum_demo.dir/sdf_helpers.cc.o
In file included from /mnt/mervin/workspaces/shambhala/drake_cmake_installed/apps/double_pendulum/double_pendulum_demo.cc:11:0:
/opt/drake/include/drake/multibody/rigid_body_plant/drake_visualizer.h:9:38: fatal error: drake/lcmt_viewer_draw.hpp: No such file or directory
compilation terminated.
```

Some typical locations for that header:

```
$ locate lcmt_viewer_draw.hpp
/mnt/mervin/workspaces/drake/build/drake/lcmtypes/drake/lcmt_viewer_draw.hpp
/mnt/mervin/workspaces/drake/build/install/include/lcmtypes/drake/lcmt_viewer_draw.hpp
/opt/drake/include/drake/lcmtypes/drake/lcmt_viewer_draw.hpp
```

**Comment by jwnimmer-tri** [comment]
Wow.  We should definitely not copy this example's code wholesale out of Drake.  The double_pendulum example code is incomplete and will be undergoing significant rework within Drake as the new SDF parser grows up.  I would suggest using RigidBodyTree in the example, since that's what most people should be using right now.  Something like an example of a `main` program that loads an SDF or URDF and forward-simulates it for a few seconds, probably with `drake_visualizer` running to watch it live.

**Comment by jwnimmer-tri** [comment]
Maybe the https://github.com/RobotLocomotion/drake/tree/master/drake/examples/particles would be a better example.  Possibly that example should even move into shambhala exclusively, since its purpose was onramp tutorial.

**Comment by stonier** [comment]
Yes, aware of the upcoming changes, but wasn't overly concerned about the *right* example yet (copy/paste is relatively free short term) but instead finding a means of express testing the lack of data support.

Definitely better is to just have a simple test that loads an sdf file in drake as that validates data installation in the most minimal way, but I'll need some additional time to write a small program to get there.

This PR for the moment will still be useful to uncover the lcmtypes problem (doesn't have to merge).

I like the idea of moving the particle demonstration.

**Comment by jamiesnape** [comment]
Depends on https://github.com/RobotLocomotion/drake/pull/6817.

**Comment by stonier** [comment]
sdformat is now linking and passing, so closing this PR.

**Pull request closed without merging**
