### PR TITLE
Use drake_PYTHON_DIRS

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Requires https://github.com/RobotLocomotion/drake/pull/8113

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/96)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature and platform review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/96#-:-L5oixi3TpAVrYQb4AMC:bgxgbg2)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[drake_cmake_installed/CMakeLists.txt, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/96#-L5pNV2hiWMQkMlQoQSC:-L5pNV2hiWMQkMlQoQSD:b94mh6k) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/857c2a5388bc6c5118b04f5adc3296a6607dc505/drake_cmake_installed/CMakeLists.txt#L47)):*
> ```CMake
> 
> find_package(PythonInterp 2.7 EXACT MODULE REQUIRED)
> set(ENV{PYTHONPATH} "${drake_PYTHON_DIRS}:$ENV{PYTHONPATH}")
> ```

One thing to note is that `set(ENV{PYTHONPATH} "<path>:$ENV{PYTHONPATH}")` does not really have much effect here and it might be better to just use  a regular variable, i.e., `set(PYTHONPATH "<path>:$ENV{PYTHONPATH}")`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/96)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/96#-:-L5pOQ7_9mRnfex0aRD4:bnfp4nl)*

**Comment by jamiesnape** [comment]
(should wait until tomorrow to merge)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/96#-:-L5pOVzBDJoGVaQd-Cr3:b-61g11e)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake_cmake_installed/CMakeLists.txt, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/96#-L5pNV2hiWMQkMlQoQSC:-L63s2nh49ik0zqRbq6q:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/857c2a5388bc6c5118b04f5adc3296a6607dc505/drake_cmake_installed/CMakeLists.txt#L47)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

One thing to note is that `set(ENV{PYTHONPATH} "<path>:$ENV{PYTHONPATH}")` does not really have much effect here and it might be better to just use  a regular variable, i.e., `set(PYTHONPATH "<path>:$ENV{PYTHONPATH}")`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/96)*

**Comment by jamiesnape** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[drake_cmake_installed/CMakeLists.txt, line 47 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/96#-L5pNV2hiWMQkMlQoQSC:-L63trNP9cElZlquLdw7:b4uvnax) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/857c2a5388bc6c5118b04f5adc3296a6607dc505/drake_cmake_installed/CMakeLists.txt#L47)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Done.
</blockquote></details>

RHS does need to be `$ENV{PYTHONPATH}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/96)*

**Pull request merged**
