### PR TITLE
bazel: Expose scalar types in custom pydrake bindings

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Example for RobotLocomotion/drake#9009
- [x] Requires RobotLocomotion/drake#9010

\cc @mposa

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/109)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for review, please.

---

Review status: all discussions resolved, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/109#-:-LF4-iu--nkAG_P79btv:b-z97laq)*

**Comment by jwnimmer-tri** [comment]
LGTM but I assume the Drake PR has to merge first.

---

Reviewed 3 of 3 files at r1.
Review status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/109#-:-LF4fXIbC6LF0_4LS2gk:b-9fjtgg)*

**Comment by EricCousineau-TRI** [comment]
Done. Re-testing in CI now.

---

Review status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/109#-:-LFhpYAN79N94Zk6lxvp:b-cgfti0)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

---

Review status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/109#-:-LFs2Y_P-6Q4SwuTif3c:bnfp4nl)*

**Pull request merged**
