### PR TITLE
Cleanup various source code (mostly) formatting issues

### PR DESCRIPTION
**Pull request by jamiesnape**
The majority, but certainly not all, of this is automated fix up. It is on my TODO list to enforce all the style checks on CI so things do not get stale again.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/94)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for review.

**Comment by EricCousineau-TRI** [comment]
:lgtm:, with a few minor comments.

---

Reviewed 13 of 23 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[drake_cmake_installed/src/find_resource/find_resource.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/94#-L5l2ilXGuaawxThzqu_:-L5l2ilYRtj5X2YCKiLc:bnze7ye) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/1d7325bba84d6ea9a3942c216ae2d234da93ba84/drake_cmake_installed/src/find_resource/find_resource.cc#L53)):*
> ```cpp
>     std::cerr << "Should have thrown" << std::endl;
>     return 1;
>   } catch (const std::runtime_error&) {
> ```

BTW This looks a tad odd?

---

*[drake_cmake_installed/src/particles/test/test_particle.cc, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/94#-L5l324y-i7tL-6mKsQz:-L5l324y-i7tL-6mKsR-:b-c3f1lb) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/aa25a8302678abd8d13db9a16062ad207b871c15/drake_cmake_installed/src/particles/test/test_particle.cc#L30)):*
> ```cpp
>  * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
>  * POSSIBILITY OF SUCH DAMAGE.
>  *****************************************************************************/
> ```

Can you add a TODO for me in this file to change it to pure C++, and not use GTest?

---

*[drake_cmake_installed/src/particles/test/test_particle.cc, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/94#-L5l2wgVemHlo-EBJa8e:-L5l2wgXjDF6Itp7Uj_7:b-bbx6a3) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/1d7325bba84d6ea9a3942c216ae2d234da93ba84/drake_cmake_installed/src/particles/test/test_particle.cc#L33)):*
> ```cpp
> 
> // clang-format off
> #include "particle.h"  // IWYU pragma: associated
> ```

BTW Shouldn't this be allowed by default? Seems odd that the linter catches this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/94#-:-L5l3K5AWz4Gw9A0qMyA:b-vqob7x)*

**Comment by jamiesnape** [comment]
Review status: 18 of 28 files reviewed at latest revision, 3 unresolved discussions.

---

*[drake_cmake_installed/src/particles/particle_test.cc, line 30 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/94#-L5l324y-i7tL-6mKsQz:-L5nnSlICicu5SnmpteH:b-gqchwq) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/aa25a8302678abd8d13db9a16062ad207b871c15/drake_cmake_installed/src/particles/particle_test.cc#L30)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can you add a TODO for me in this file to change it to pure C++, and not use GTest?
</blockquote></details>

I added it in the CMakeLists.txt. There are multiple files.

---

*[drake_cmake_installed/src/particles/particle_test.cc, line 33 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/94#-L5l2wgVemHlo-EBJa8e:-L5nnXxdwrbxg8qEQBNP:bx28y0o) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/1d7325bba84d6ea9a3942c216ae2d234da93ba84/drake_cmake_installed/src/particles/particle_test.cc#L33)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Shouldn't this be allowed by default? Seems odd that the linter catches this.
</blockquote></details>

Seems we were not following the Google naming convention for tests. Should be fixed by the latest commit.

---

*[drake_cmake_installed/src/find_resource/find_resource.cc, line 53 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/94#-L5l2ilXGuaawxThzqu_:-L5neXb9oB6cTNmlsek-:b-x6ecqt) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/1d7325bba84d6ea9a3942c216ae2d234da93ba84/drake_cmake_installed/src/find_resource/find_resource.cc#L53)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW This looks a tad odd?
</blockquote></details>

BTW True, but it keeps `clang-format` happy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/94)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 15 of 17 files at r3.
Review status: 27 of 28 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/94)*

**Comment by EricCousineau-TRI** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/94)*

**Pull request merged**
