### PR TITLE
[WIP] drake_cmake_installed: Add pybind11 in sync with Drake's version. Add simple example

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Addresses https://github.com/RobotLocomotion/drake/issues/7856, part (b).

Requires https://github.com/RobotLocomotion/drake/pull/8107

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/95)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Can you hold on this. You can't actually add an external project to `drake_cmake_installed` this way.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/95#-:-L5nmydKlGjgU7-Difhz:b-xwi5gb)*

**Comment by EricCousineau-TRI** [comment]
Yeah... I couldn't think of a clean way to incorporate that. I guess there could be two levels of indirection (subprojects), but that sounds ugly.

> Can you hold on this.

This is aimed primarily for Russ for the Underactuated course; I believe he can hardcode the `pybind11` info if necessary, but my assumption is that these hashes will move a few times during the course.

That being said, even if we can't do this for `drake_cmake_installed`, I'd prefer to still have *something* working, and then refine that if possible?

This is actually related to the NumPy dtype issue; if AutoDiff / Symbolic matrices cannot be mutated as references in Python, and requires a semantic change of `pydrake`, then as a workaround Russ could author the classes in C++ (possibly delegating to Python callbacks), requiring custom downstream Python bindings in Underactuated.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/95#-:-L5oXqdHeJfE5CDqfFSP:b-m7b3z)*

**Comment by jamiesnape** [comment]
You are not going to be able to get something working for `drake_cmake_installed` without basically turning it into an ugly version of `drake_cmake_external` minus the download, and you are not going to be able to get `drake_cmake_external` working because you need `drake` to be downloaded to get the SHA for a parallel call to `ExternalProject_Add`.

Maybe with some new functionality CMake 3.11 you could get something working, but with CMake 3.5, you are out of luck save for maybe a few hacks that are far more brittle than Russ updating the SHA of the Git repo by hand.

Presumably are wanting to embed the version of pybind11 that was used into pydrake itself (whether in the Python or C++ code). Maybe you should do that while I think of a solution. At the very least Russ could then query it with Python and inject that into his build.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/95#-:-L5o_NS4blaB_rMR8yxR:bp1sty)*

**Comment by EricCousineau-TRI** [comment]
Sounds good!

**Pull request closed without merging**
