### PR TITLE
Rewind to a commit prior to the breaking new_local_repository change

### PR DESCRIPTION
**Pull request by stonier**
Temporarily gets CI working again - see #45.

### CODE REVIEW

**Comment by jamiesnape** [comment]
CI is still not happy.

**Comment by stonier** [comment]
I know, left a comment over in the issue and sending a (temporary) fix to Drake.

**Comment by stonier** [comment]
Fix in Drake going in at https://github.com/robotlocomotion/drake/pull/7257

**Comment by stonier** [comment]
Closing, #48 instead.

**Pull request closed without merging**
