### PR TITLE
Remove support for Trusty

### PR DESCRIPTION
**Pull request by jamiesnape**
Per RobotLocomotion/drake#5012, Drake no longer supports Trusty. There will be a followup PR to reenable Travis CI support using Docker images.

### CODE REVIEW

**Comment by stonier** [comment]
@jamiesnape Need to fix the CI. Looks like the PR's are getting thwarted by an existing 'build' directory ([here](https://drake-jenkins.csail.mit.edu/job/RobotLocomotion/job/drake-shambhala/job/PR-40/1/console)). Why did we not see this before - now due to multiple PR's in flight?

Also the master build has problems of it's own, so it likely won't build here either. e.g. [here](https://drake-jenkins.csail.mit.edu/job/RobotLocomotion/job/drake-shambhala/job/master/17/console). That seems like a c++14 option was not flagged, but I do not see any discrepancy between the CI build which fails and my local build which works.

**Comment by jamiesnape** [comment]
I don't see the build directory issue, but the other breakages look like they are Drake related.

**Comment by stonier** [comment]
Sorry, copy pasta mistake. The build directory problem is exactly this failure in this PR, i.e. [here](https://drake-jenkins.csail.mit.edu/job/RobotLocomotion/job/drake-shambhala/job/PR-40/2/console).

**Comment by jamiesnape** [comment]
(Travis CI will not pass since it needs disabling for now, of course)

**Pull request merged**
