### PR TITLE
Fix inconsistent licenses

### PR DESCRIPTION
**Pull request by jamiesnape**
Since we have different copyright holders per file, the licenses had become internally inconsistent. Substituting the name of a copyright holder for "copyright holder(s)" (the license itself is inconsistent in pluralization, which we have to live with) also appears to have broken the GitHub parsing of the license. Not that I am a lawyer, but this should be cosmetic in the overall meaning of the license.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/93)

### CODE REVIEW

**Comment by jamiesnape** [comment]
+@EricCousineau-TRI for review.

**Comment by EricCousineau-TRI** [comment]
Reviewed 57 of 57 files at r1.
Review status: 57 of 58 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[.gitignore, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/93#-L5VT65Qd26GOOeg7BSa:-L5VT65Qd26GOOeg7BSb:b-t3tx76) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/9a5019ebd06743ee7abfa95f841e47d4d0654088/.gitignore#L1)):*
> ```
> # Compiled Object files
> ```

Can we defer the deletion of this file to another PR?

---

*[drake_cmake_installed/src/particles/test/test_particle.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/93#-L5VSwd3dNrn7SStYKY8:-L5VSwd3dNrn7SStYKY9:bv1re51) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/ab8ef516fb3dcec4bc9e4bbfc4217e25ac41cb34/drake_cmake_installed/src/particles/test/test_particle.cc#L8)):*
> ```cpp
> 
> #include <drake/systems/framework/basic_vector.h>
> /*****************************************************************************
> ```

BTW Is there a reason that this does not precede the includes? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/93)*

**Comment by jamiesnape** [comment]
Review status: 57 of 58 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[.gitignore, line 1 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/93#-L5VT65Qd26GOOeg7BSa:-L5VUp-NqsTDRZIJ5Wtz:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/9a5019ebd06743ee7abfa95f841e47d4d0654088/.gitignore#L1)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

Can we defer the deletion of this file to another PR?
</blockquote></details>

Done.

---

*[drake_cmake_installed/src/particles/test/test_particle.cc, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/93#-L5VSwd3dNrn7SStYKY8:-L5VUpXccvwQe0bFzXbi:bym1tos) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/ab8ef516fb3dcec4bc9e4bbfc4217e25ac41cb34/drake_cmake_installed/src/particles/test/test_particle.cc#L8)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

BTW Is there a reason that this does not precede the includes? 
</blockquote></details>

BTW Apparently my text editor window was not scrolled to the top of the page.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/93)*

**Comment by EricCousineau-TRI** [comment]
:lgtm: on a technical level - thanks!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/93#-:-L5VZ_5Trwt1mibJUAYB:b-ehya97)*

**Pull request merged**
