### PR TITLE
Fix Travis CI / macOS builds

### PR DESCRIPTION
**Pull request by soonho-tri**
See https://github.com/Homebrew/homebrew-core/issues/26358

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/102)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/102#-:-LAnZLo74BHmd5Fascky:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[scripts/continuous_integration/travis_ci/setup, line 41 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/102#-LAn_Nr93jEcDbi8GsUH:-LAn_Nr93jEcDbi8GsUI:b-74865t) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/d6c295a830eb0f0d20d8ddeadad1344c09d658c2/scripts/continuous_integration/travis_ci/setup#L41)):*
> ```
> 
> # https://github.com/travis-ci/travis-ci/issues/8826
> brew cask uninstall oclint
> ```

Now Travis-CI is not happy with this hack:

```
+brew cask uninstall oclint
==> Uninstalling Cask oclint
==> Unlinking Binary '/usr/local/bin/oclint'.
==> Unlinking Binary '/usr/local/bin/oclint-json-compilation-database'.
==> Unlinking Binary '/usr/local/bin/oclint-xcodebuild'.
==> Unlinking Binary '/usr/local/lib/oclint'.
==> Unlinking Binary '/usr/local/include/c++'.
==> Purging files for version 0.11,15.6.0 of Cask oclint
+/usr/local/opt/python/libexec/bin/pip uninstall -y scipy numpy
Cannot uninstall requirement scipy, not installed
```

Should I add `|| true` here?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/102)*

**Comment by soonho-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[scripts/continuous_integration/travis_ci/setup, line 41 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/102#-LAn_Nr93jEcDbi8GsUH:-LAn_eAb5USoNaD7pLSk:b-32gx60) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/d6c295a830eb0f0d20d8ddeadad1344c09d658c2/scripts/continuous_integration/travis_ci/setup#L41)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Now Travis-CI is not happy with this hack:

```
+brew cask uninstall oclint
==> Uninstalling Cask oclint
==> Unlinking Binary '/usr/local/bin/oclint'.
==> Unlinking Binary '/usr/local/bin/oclint-json-compilation-database'.
==> Unlinking Binary '/usr/local/bin/oclint-xcodebuild'.
==> Unlinking Binary '/usr/local/lib/oclint'.
==> Unlinking Binary '/usr/local/include/c++'.
==> Purging files for version 0.11,15.6.0 of Cask oclint
+/usr/local/opt/python/libexec/bin/pip uninstall -y scipy numpy
Cannot uninstall requirement scipy, not installed
```

Should I add `|| true` here?
</blockquote></details>

Oops, not this one but the one below.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/102)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[scripts/continuous_integration/travis_ci/setup, line 41 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/102#-LAn_Nr93jEcDbi8GsUH:-LAn_vnzADwRkmU_2X0z:b4glisf) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/d6c295a830eb0f0d20d8ddeadad1344c09d658c2/scripts/continuous_integration/travis_ci/setup#L41)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Oops, not this one but the one below.
</blockquote></details>

Sure, though we may need to split the `scipy` and `numpy` uninstalls into separate lines as well.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/102)*

**Comment by soonho-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/continuous_integration/travis_ci/setup, line 41 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/102#-LAn_Nr93jEcDbi8GsUH:-LAnahTlAEzOA0AHGBmT:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/d6c295a830eb0f0d20d8ddeadad1344c09d658c2/scripts/continuous_integration/travis_ci/setup#L41)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Sure, though we may need to split the `scipy` and `numpy` uninstalls into separate lines as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/102)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/102)*

**Comment by soonho-tri** [comment]
https://travis-ci.org/RobotLocomotion/drake-shambhala/builds/370211981?utm_source=github_status&utm_medium=notification

```
Error: No such file or directory - /usr/local/opt/mercurial/bin/hg
```

What about this? Do we need mercurial?

**Comment by soonho-tri** [comment]
Possibly related: https://github.com/Homebrew/homebrew-core/issues/24978#issuecomment-378668609

But I still have no idea why mercurial is in the scene...

**Comment by jamiesnape** [comment]
We don't need mercurial.

**Comment by jamiesnape** [comment]
...but I guess we just force reinstall if it gets things working again.

**Comment by jamiesnape** [comment]
Actually change `/usr/local/opt/python/libexec/bin/pip` to `/usr/local/bin/pip` and see if that works.

**Comment by jamiesnape** [comment]
The `brew upgrade python || true` is changing the `pip` from Python 2 to Python 3, so the Python 2 `numpy` is not being uninstalled anymore.

**Comment by soonho-tri** [comment]
I just updated the PR... but if the current one is not going to work, I'll try:

```
# https://github.com/travis-ci/travis-ci/issues/8826
brew cask uninstall oclint

# https://github.com/travis-ci/travis-ci/issues/6688
/usr/local/bin/pip uninstall -y scipy || true
/usr/local/bin/pip uninstall -y numpy || true

# https://github.com/Homebrew/homebrew-core/issues/26358
brew upgrade python || true
```

**Comment by jamiesnape** [comment]
Running out of ideas. Apply the sledgehammer:
```
rm -f /usr/local/bin/f2py
rm -rf /usr/local/lib/python2.7/site-packages/numpy-*-py2.7.egg-info
rm -rf /usr/local/lib/python2.7/site-packages/numpy/ 
rm -rf /usr/local/lib/python2.7/site-packages/scipy-*-py2.7.egg-info
rm -rf /usr/local/lib/python2.7/site-packages/scipy/ 
```

**Comment by soonho-tri** [comment]
right before we call `./scripts/continuous_integration/common/mac`?

**Comment by jamiesnape** [comment]
You missed the critical `rm -f /usr/local/bin/f2py`, I think. The `pip uninstall`s can go, they will just always fail.

**Comment by soonho-tri** [comment]
CI is happy finally.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[scripts/continuous_integration/travis_ci/setup, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/102#-LAs7sUGCPMWo_qJZROA:-LAs7sUGCPMWo_qJZROB:b-quy9p5) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/9e37185f195c42fee08031672531a81de06e9495/scripts/continuous_integration/travis_ci/setup#L53)):*
> ```
> 
> # https://github.com/Homebrew/homebrew-core/issues/24978
> brew uninstall --force mercurial; brew install mercurial
> ```

BTW Can we split this onto two lines instead of the semicolon?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/102#-:-LAs82DNBgA3Md22i4GJ:bnfp4nl)*

**Comment by soonho-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/continuous_integration/travis_ci/setup, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/102#-LAs7sUGCPMWo_qJZROA:-LAsHSx32n9duRiGNJhS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/9e37185f195c42fee08031672531a81de06e9495/scripts/continuous_integration/travis_ci/setup#L53)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW Can we split this onto two lines instead of the semicolon?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/102)*

**Pull request merged**
