### PR TITLE
bazel: Add example consuming pydrake

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri for review, please.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104#-:-LD7krO28x1t5sxABE1m:b-z97laq)*

**Comment by jwnimmer-tri** [comment]
:lgtm:

FYI remember to run `buildifier` by hand, since I don't think its automated yet in Shambhala.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drake_bazel_external/apps/BUILD.bazel, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104#-LD7vUdx-HphXavsQa5a:-LD7vUdx-HphXavsQa5b:b68nl54) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/4ae6894f4932bd2bae5ac05e9180dbd0a2c6c52a/drake_bazel_external/apps/BUILD.bazel#L43)):*
> ```Python
> )
> 
> # Make a simple Python application.
> ```

FYI You could imagine adding a short comment here indicating to run `bazel-bin/apps/simple_logging_example` when a user wants to invoke this, since that might not be what users would naively assume, especially more novice Bazel users.

---

*[drake_bazel_external/apps/BUILD.bazel, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104#-LD7uoTYB-5d7mPm5hAB:-LD7uoTZ55YAstiZ982T:bmt8afq) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/4ae6894f4932bd2bae5ac05e9180dbd0a2c6c52a/drake_bazel_external/apps/BUILD.bazel#L53)):*
> ```Python
> 
> # Run the applications to make sure they complete successfully.
> # N.B. For actual development, you should prefer `*_test` targets.
> ```

BTW This is a bit confusing, because the below targets _are_ `*_test` targets already, but this seems to imply actual development should do otherwise.

---

*[drake_bazel_external/apps/BUILD.bazel, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104#-LD7v6BPBAirBPKjTYhR:-LD7v6BPBAirBPKjTYhS:bqcitab) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/4ae6894f4932bd2bae5ac05e9180dbd0a2c6c52a/drake_bazel_external/apps/BUILD.bazel#L62)):*
> ```Python
> sh_test(
>     name = "simple_logging_example_test",
>     srcs = ["py_binary_test.sh"],
> ```

FYI I think this could be called just `exec.sh`, for simplicity / clarity?

---

*[drake_bazel_external/apps/py_binary_test.sh, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104#-LD7vxDXD5GByZU4cIar:-LD7vxDXD5GByZU4cIas:b-meax73) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/4ae6894f4932bd2bae5ac05e9180dbd0a2c6c52a/drake_bazel_external/apps/py_binary_test.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> # Copyright (c) 2017, Massachusetts Institute of Technology.
> ```

Copyright is `Toyota Research Institute`.

BTW 2018 (unless you copied this from somewhere else?)

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104#-:-LD7vH4fA4ad0T2NJMAS:b-ih9esk)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake_bazel_external/apps/BUILD.bazel, line 43 at r1](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104#-LD7vUdx-HphXavsQa5a:-LD8EMCl3WWZR9FVY9-N:b66c28f) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/4ae6894f4932bd2bae5ac05e9180dbd0a2c6c52a/drake_bazel_external/apps/BUILD.bazel#L43)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI You could imagine adding a short comment here indicating to run `bazel-bin/apps/simple_logging_example` when a user wants to invoke this, since that might not be what users would naively assume, especially more novice Bazel users.
</blockquote></details>

Done. Added to `README` to expand on this a bit more. I'm a bit hesitant to say that users should always use `bazel run`, because we may have not yet fully proofed all of our binaries against the `PWD` that a script is run in.
(e.g. AFAIK `FindResource` works under `bazel test`, but not `bazel run` - which is something we'd probably want to fix soon.)

---

*[drake_bazel_external/apps/BUILD.bazel, line 53 at r1](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104#-LD7uoTYB-5d7mPm5hAB:-LD8EiNKDHLxhsrNetaY:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/4ae6894f4932bd2bae5ac05e9180dbd0a2c6c52a/drake_bazel_external/apps/BUILD.bazel#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW This is a bit confusing, because the below targets _are_ `*_test` targets already, but this seems to imply actual development should do otherwise.
</blockquote></details>

Done.

---

*[drake_bazel_external/apps/BUILD.bazel, line 62 at r1](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104#-LD7v6BPBAirBPKjTYhR:-LD8EkMk8odAw9R2wsH2:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/4ae6894f4932bd2bae5ac05e9180dbd0a2c6c52a/drake_bazel_external/apps/BUILD.bazel#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I think this could be called just `exec.sh`, for simplicity / clarity?
</blockquote></details>

Done.

---

*[drake_bazel_external/apps/py_binary_test.sh, line 3 at r1](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104#-LD7vxDXD5GByZU4cIar:-LD8ElVx5XXpm_suMyBK:b-r08yfo) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/4ae6894f4932bd2bae5ac05e9180dbd0a2c6c52a/drake_bazel_external/apps/py_binary_test.sh#L3)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Copyright is `Toyota Research Institute`.

BTW 2018 (unless you copied this from somewhere else?)
</blockquote></details>

Done. D'oh!

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104)*

**Comment by jwnimmer-tri** [comment]
Reviewed 3 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/104)*

**Pull request merged**
