### PR TITLE
Use specific components from PCL. Add Drake camera simulation.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This is a simple test in relation to the discussion in RobotLocomotion/drake#7702.

\cc @RussTedrake

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/76)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
Currently segfaults when destructing, not sure why:
https://gist.github.com/EricCousineau-TRI/2bc264d2532b6bf0e01676edf9f32af0

**Comment by jwnimmer-tri** [comment]
That looks a lot like the RobotLocomotion/drake#7935 failure mode with a hidden display?

**Comment by jamiesnape** [comment]
> That looks a lot like the RobotLocomotion/drake#7935 failure mode with a hidden display?

RobotLocomotion/drake#7908, actually, I think my comment was misinterpreted and we ended up with duplicate issues.

**Comment by jwnimmer-tri** [comment]
Agreed.

**Comment by jamiesnape** [comment]
I think I would prefer to split `test_pcl` and `test_drake_camera` into separate files.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake_cmake_installed/src/pcl/simple_pcl_example.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-L4rinzlZEhqlB6quMPW:-L4rinzlZEhqlB6quMPX:bqkc6gs) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/5940e1cf868129e21d6902ccaad2af5328cbee52/drake_cmake_installed/src/pcl/simple_pcl_example.cc#L44)):*
> ```cpp
> #include <iostream>
> #include <random>
> #include <memory>
> ```

Alphabetize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-:-L4rj6nBqSVQ2BgkH7hk:bdcpvhi)*

**Comment by EricCousineau-TRI** [comment]
Is there a reason why?

I'm trying to think of a good split that shows both a simple example and still tests what I want; I've split it into to `test_pcl` and `test_drake_camera`, and it feels weird to either (a) duplicate `test_pcl` between this and `simple_pcl_example` or (b) include `test_pcl.h` and call it in `simple_pcl_example - main` and something like `test_drake_and_pcl - main`.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-:-L4s0A9bKfO3_xZ06s0D:b-reembl)*

**Comment by EricCousineau-TRI** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake_cmake_installed/src/pcl/simple_pcl_example.cc, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-L4rinzlZEhqlB6quMPW:-L4s6wVcyNuN5F9HjsUZ:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/5940e1cf868129e21d6902ccaad2af5328cbee52/drake_cmake_installed/src/pcl/simple_pcl_example.cc#L44)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Alphabetize
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76)*

**Comment by jamiesnape** [comment]
Maybe I am missing something, but I do not see how the two examples are connected. `test_drake_camera` does not even appear to use PCL.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-:-L4sBnpkX2K5g5AJJHMk:b-8lnci)*

**Comment by EricCousineau-TRI** [comment]
I had an apparently irrational superstition that the binary had be linked with code that consumes PCL to ensure that the linking does not get optimized out. Realized that was ill-founded, so I've split 'em. Sorry about that!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-:-L4sKNx0RGEDaV4By7lT:b-93j4j1)*

**Comment by EricCousineau-TRI** [comment]
Rebased #90 on top of this revision.

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[drake_cmake_installed/src/pcl/test_drake_camera.cc, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-L4sLRXCfH-dSoUnbLtc:-L4sLRXCfH-dSoUnbLtd:bgqufvp) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/dcacbfdf71b6382c67fb8e21f69b34f1ce368032/drake_cmake_installed/src/pcl/test_drake_camera.cc#L2)):*
> ```cpp
> /*****************************************************************************
>  * Copyright (c) 2017, Toyota Research Institute.
> ```

BTW 2018

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-:-L4sLmX6cECxxRVGbrxb:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
Uh oh - it looks like CircleCI also suffers from the XVFB thing... Is there any option to enable this, or should we just punt on this being a `ctest`?

**Comment by EricCousineau-TRI** [comment]
Punting on `add_test` for `test_drake_camera` -- however, it looks like TravisCI does test it successfully, so I may briefly look into enabling this only on Travis.

**Comment by jamiesnape** [comment]
I can get it working on CircleCI easy enough. It will be later today, though.

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake_cmake_installed/src/pcl/CMakeLists.txt, line 54 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-L4v8fraqg4MtQoon92q:-L4v8fraqg4MtQoon92r:b4uzj9l) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/52327e28cc45854a62e2e4e0df6030c5ddc127ae/drake_cmake_installed/src/pcl/CMakeLists.txt#L54)):*
> ```CMake
> 
> add_executable(test_drake_camera test_drake_camera.cc)
> target_link_libraries(test_drake_camera drake::drake ${PCL_LIBRARIES})
> ```

So this is supposed to be a repo of exemplary uses of Drake and unused PCL linker flags are not really exemplary. If we really want to test whether the linker flag is an issue then there should be some meaningful usage of PCL within that test (not just unrelated code in the same file).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76)*

**Comment by EricCousineau-TRI** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake_cmake_installed/src/pcl/CMakeLists.txt, line 54 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-L4v8fraqg4MtQoon92q:-L4vEYHTIvp2hQek6t6u:b-tstwj0) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/52327e28cc45854a62e2e4e0df6030c5ddc127ae/drake_cmake_installed/src/pcl/CMakeLists.txt#L54)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

So this is supposed to be a repo of exemplary uses of Drake and unused PCL linker flags are not really exemplary. If we really want to test whether the linker flag is an issue then there should be some meaningful usage of PCL within that test (not just unrelated code in the same file).
</blockquote></details>

I've added a TODO to the example file. Is that sufficient for now?

---

*[drake_cmake_installed/src/pcl/test_drake_camera.cc, line 2 at r2](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-L4sLRXCfH-dSoUnbLtc:-L4vEY5eubC4yn9-g9fE:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/dcacbfdf71b6382c67fb8e21f69b34f1ce368032/drake_cmake_installed/src/pcl/test_drake_camera.cc#L2)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

BTW 2018
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76)*

**Comment by EricCousineau-TRI** [comment]
if you would like non-trivial code PCL code with Drake, I'm tinkering with it now - but I could always submit it as a chaser PR :)

**Comment by jamiesnape** [comment]
A follow-up PR would be good.

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake_cmake_installed/CMakeLists.txt, line 36 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-L4vKezzM-yByImWN2YE:-L4vKezzM-yByImWN2YF:b-gqfboq) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/13a806f1cd676915fbf39cddf8988853ba1d8ca4/drake_cmake_installed/CMakeLists.txt#L36)):*
> ```CMake
> project(drake_cmake_installed)
> 
> set(RUN_X11_TESTS OFF CACHE BOOL "Run tests which require X11")
> ```

`option(RUN_X11_TESTS "Run tests that require X11" OFF)`, though the tests don't require X11 on Mac per se, but I guess this is fine (it is temporary anyway).

---

*[drake_cmake_installed/src/pcl/CMakeLists.txt, line 54 at r3](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-L4v8fraqg4MtQoon92q:-L4vKQOeTcd9HuNd3UY1:bb77ufg) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/52327e28cc45854a62e2e4e0df6030c5ddc127ae/drake_cmake_installed/src/pcl/CMakeLists.txt#L54)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I've added a TODO to the example file. Is that sufficient for now?
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-:-L4vKTnKDTYlB0wLcNEL:b5wptxs)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake_cmake_installed/CMakeLists.txt, line 36 at r4](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76#-L4vKezzM-yByImWN2YE:-L4vNSWXsI1ZsINb-gLS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/13a806f1cd676915fbf39cddf8988853ba1d8ca4/drake_cmake_installed/CMakeLists.txt#L36)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`option(RUN_X11_TESTS "Run tests that require X11" OFF)`, though the tests don't require X11 on Mac per se, but I guess this is fine (it is temporary anyway).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76)*

**Comment by jamiesnape** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/76)*

**Pull request merged**
