### PR TITLE
Add missing file headers

### PR DESCRIPTION
**Pull request by jamiesnape**

### CODE REVIEW

**Comment by stonier** [comment]
:LGTM: and can get shunted in without having to wait for the CI breakages to resolve.

**Comment by stonier** [comment]
one thing, do we still need that dockerfile?

**Comment by jamiesnape** [comment]
We do. It is not used dynamically, but the image that CircleCI uses is built from it.

**Comment by stonier** [comment]
Ah, got it. Forgot CircleCI was using docker.

**Comment by jamiesnape** [comment]
Merging documentation-only changes.

**Pull request merged**
