### PR TITLE
Add downstream Python test.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Currently the resource in question is broken.

Relates https://github.com/RobotLocomotion/drake-shambhala/issues/9

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/85)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@fbudin69500 for feature review, please (if you have time).

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-:-L3EVaPFYpa630P0bC77:b85lxod)*

**Comment by jwnimmer-tri** [comment]
FYI I am fine with having Shambhala have as many tests as we want, but in general we should have the Drake self-tests catch things like this pre-merge to the extent practical.

**Comment by EricCousineau-TRI** [comment]
Sounds good!

It'd still be nice, though, if all unittests were run on CI (e.g. ensuring that GTest is always found on CI, which may have not been the case?)
See #86 #87

**Comment by EricCousineau-TRI** [comment]
Updated since #7809 is fixed.

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drake_cmake_installed/CMakeLists.txt, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4reOtCBv_1tfqxz5j2:-L4reOtCBv_1tfqxz5j3:bibo1m1) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/CMakeLists.txt#L44)):*
> ```CMake
> 
> set(_python_version 2.7)
> find_package(PythonInterp ${_python_version} MODULE REQUIRED)
> ```

find_package(PythonInterp 2.7 EXACT MODULE REQUIRED)

---

*[drake_cmake_installed/CMakeLists.txt, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rea7cdef0QJ9SV_vJ:-L4rea7cdef0QJ9SV_vK:b-mwnhaw) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/CMakeLists.txt#L46)):*
> ```CMake
> find_package(PythonInterp ${_python_version} MODULE REQUIRED)
> set(_drake_sitepackages
>     "${drake_DIR}/../../python${_python_version}/site-packages")
> ```

`${drake_DIR}/../../python${PYTHON_VERSION_MAJOR }.${PYTHON_VERSION_MINOR}/site-packages`, but create an issue to define a variable something `DRAKE_PYDRAKE_DIR` in `drake.cps` (I forget the naming convention we have used so far).

---

*[drake_cmake_installed/CMakeLists.txt, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rdjiBa76zv31HPH2J:-L4rdjiBa76zv31HPH2K:b2yw5vp) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/CMakeLists.txt#L48)):*
> ```CMake
>     "${drake_DIR}/../../python${_python_version}/site-packages")
> get_filename_component(_drake_sitepackages "${_drake_sitepackages}" ABSOLUTE)
> # TODO(eric.cousineau): Make this a `pydrake` package, than can be depended on,
> ```

This functionality does exist in CMake, so not an actionable TODO unless you want us to add the functionality and move to a newer CMake (which I doubt you do just for this).

---

*[drake_cmake_installed/src/find_resource/CMakeLists.txt, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rfg2KueQto7BsCVyf:-L4rfg2KueQto7BsCVyg:bhkqu1g) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/src/find_resource/CMakeLists.txt#L45)):*
> ```CMake
> add_test(
>     NAME test_find_resource_py
>     COMMAND ${PYTHON_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/test_find_resource.py)
> ```

`${PYTHON_EXECUTABLE}` `${CMAKE_CURRENT_SOURCE_DIR}/test_find_resource.py`

---

*[drake_cmake_installed/src/find_resource/CMakeLists.txt, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rfoMXQPCFho_QdCFT:-L4rfoMXQPCFho_QdCFU:b-m0d6n7) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/src/find_resource/CMakeLists.txt#L49)):*
> ```CMake
>     test_find_resource_py
>     PROPERTIES
>         ENVIRONMENT PYTHONPATH=$ENV{PYTHONPATH})
> ```

`"PYTHONPATH=$ENV{PYTHONPATH}"`

---

*[drake_cmake_installed/src/find_resource/test_find_resource.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rfOlr8eu7PFuMUDEI:-L4rfOlr8eu7PFuMUDEJ:b-ancq0r) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/src/find_resource/test_find_resource.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

We don't need a shebang. Replace with
```
# -*- mode: python -*-
# vi: set ft= python :
```

---

*[drake_cmake_installed/src/find_resource/test_find_resource.py, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rdXLEialPcEZKDrPa:-L4rdXLEialPcEZKDrPb:bh1u68l) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/src/find_resource/test_find_resource.py#L6)):*
> ```Python
> 
> import pydrake
> from pydrake import common
> ```

Do we need all these imports?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[drake_cmake_installed/CMakeLists.txt, line 44 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4reOtCBv_1tfqxz5j2:-L4s4zi81He_W60wX1En:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/CMakeLists.txt#L44)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

find_package(PythonInterp 2.7 EXACT MODULE REQUIRED)
</blockquote></details>

Done.

---

*[drake_cmake_installed/CMakeLists.txt, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rea7cdef0QJ9SV_vJ:-L4s4z8A7saf04aIAEpp:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/CMakeLists.txt#L46)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`${drake_DIR}/../../python${PYTHON_VERSION_MAJOR }.${PYTHON_VERSION_MINOR}/site-packages`, but create an issue to define a variable something `DRAKE_PYDRAKE_DIR` in `drake.cps` (I forget the naming convention we have used so far).
</blockquote></details>

Done.

---

*[drake_cmake_installed/CMakeLists.txt, line 48 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rdjiBa76zv31HPH2J:-L4s4zN6u6inc0BdonY4:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/CMakeLists.txt#L48)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

This functionality does exist in CMake, so not an actionable TODO unless you want us to add the functionality and move to a newer CMake (which I doubt you do just for this).
</blockquote></details>

Done.

---

*[drake_cmake_installed/src/find_resource/CMakeLists.txt, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rfg2KueQto7BsCVyf:-L4s4bb8yhYH84ZcCkL3:b-uwm9wp) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/src/find_resource/CMakeLists.txt#L45)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`${PYTHON_EXECUTABLE}` `${CMAKE_CURRENT_SOURCE_DIR}/test_find_resource.py`
</blockquote></details>

I see no difference - can I ask what the defect is? (added a linebreak for wrapping)

---

*[drake_cmake_installed/src/find_resource/CMakeLists.txt, line 49 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rfoMXQPCFho_QdCFT:-L4s5P0BUaWZz7Lqe4oO:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/src/find_resource/CMakeLists.txt#L49)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`"PYTHONPATH=$ENV{PYTHONPATH}"`
</blockquote></details>

Done.

---

*[drake_cmake_installed/src/find_resource/test_find_resource.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rfOlr8eu7PFuMUDEI:-L4s58E_tJQqLGX89Lwl:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/src/find_resource/test_find_resource.py#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We don't need a shebang. Replace with
```
# -*- mode: python -*-
# vi: set ft= python :
```
</blockquote></details>

Done.

---

*[drake_cmake_installed/src/find_resource/test_find_resource.py, line 6 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rdXLEialPcEZKDrPa:-L4s58QGlDXgJYbMkYZs:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/src/find_resource/test_find_resource.py#L6)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Do we need all these imports?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake_cmake_installed/src/find_resource/CMakeLists.txt, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rfg2KueQto7BsCVyf:-L4sDWpjF1R92-D7LypI:b-x7l9ff) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/src/find_resource/CMakeLists.txt#L45)):*
<details><summary><i>Previously, EricCousineau-TRI wrote…</i></summary><blockquote>

I see no difference - can I ask what the defect is? (added a linebreak for wrapping)
</blockquote></details>

Sorry, I meant to add double quotes.

```"${PYTHON_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/test_find_resource.py"```
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-:-L4sDk-SuZpPPtGyd6mN:bnfp4nl)*
<!-- Sent from Reviewable.io -->

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake_cmake_installed/src/find_resource/CMakeLists.txt, line 45 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85#-L4rfg2KueQto7BsCVyf:-L4sGwZPSmaDV-4YD1oP:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/7e26288190176cd19fe5d25ec2fba52ad5b27af1/drake_cmake_installed/src/find_resource/CMakeLists.txt#L45)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Sorry, I meant to add double quotes.

```"${PYTHON_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/test_find_resource.py"```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85)*

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/85)*

**Pull request merged**
