### PR TITLE
 cmake: Add example of custom bindings using drake + pydrake 

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Requires:
- [x] https://github.com/robotlocomotion/drake/pull/8264
- [x] https://github.com/RobotLocomotion/drake/pull/8860

Supersedes https://github.com/RobotLocomotion/drake-shambhala/pull/95

Relates:
https://github.com/pybind/pybind11/pull/1373
https://github.com/pybind/pybind11/pull/1367

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/98)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jamiesnape for feature review, please

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-:-L6yQZf-56spMIOKFvWJ:b-yw2yrw)*

**Comment by RussTedrake** [comment]
Nice!  This is going to be very useful for me.  thanks!

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-:-L6zwzW9_nnkRn1Qq_jI:bafi82y)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[drake_cmake_external/CMakeLists.txt, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-r33E9lIbfWSwYAVW:-L7-r33FjUBQyazLWgXt:bc7ddrv) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_external/CMakeLists.txt#L36)):*
> ```CMake
> # `ExternalProject_Add` here, and add `drake_shambhala` afterwards (also as a
> # external project) which depends on these external projects, so that it can
> # effectively build the external projects during the configuration stage.
> ```

Remove. Does not add anything and quite possibly confuses things.

---

*[drake_cmake_installed/CMakeLists.txt, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-rKwPckWkNHZa1XRq:-L7-rKwPckWkNHZa1XRr:bi8p4hx) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/CMakeLists.txt#L46)):*
> ```CMake
> # This must be specified before `drake`, so that `pybind11` does not find
> # another version.
> find_package(PythonInterp 2.7 EXACT MODULE REQUIRED)
> ```

This is exactly why you should not be throwing unnecessary dependencies into `drake-config.cmake`.

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-sDI5SqMMzlhtWAtW:-L7-sDI6EdhWBOwsQVch:b1hbu5f) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L8)):*
> ```CMake
> # which is empty, relying on libraries to link `pybind11_LIBRARIES` to get the
> # proper include directories; `pybind11_add_module` does not use
> # `pybind11_LIBRARIES`.
> ```

Remove. You are misunderstanding how `target_link_libraries` works. The name is a legacy and you should never need to use a `pybind11_INCLUDE_DIRS` variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 2 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-sqTKCsuj_EPInGqg:-L7-sqTKCsuj_EPInGqh:b-otlw7l) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L2)):*
> ```CMake
> find_package(pybind11 CONFIG REQUIRED)
> include(pybind11Tools)
> ```

Remove. This is already included by the `find_package` call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by jamiesnape** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[drake_cmake_installed/src/simple_bindings/test_example_module.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-u9h1vjti_j9P5-Km:-L7-u9h1vjti_j9P5-Kn:b1vrh5k) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/test_example_module.py#L1)):*
> ```Python
> from example_module import SimpleAdder
> ```

Name the file `example_module_test.py` and add a short docstring to the top of the file. Also `pylint` is really not happy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-wRH_dEoMAw--uf3t:-L7-wRH_dEoMAw--uf3u:b-rstvjn) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L1)):*
> ```CMake
> find_package(pybind11 CONFIG REQUIRED)
> ```

Add the copyright and license header.

---

*[drake_cmake_installed/src/simple_bindings/example_module.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-wPDNVh-choXVJGiH:-L7-wPDNVh-choXVJGiI:b-rstvjn) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/example_module.cc#L1)):*
> ```cpp
> #include <pybind11/pybind11.h>
> ```

Add the copyright and license header.

---

*[drake_cmake_installed/src/simple_bindings/test_example_module.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-u9h1vjti_j9P5-Km:-L7-wFmtUfaFxPOQnXUO:b-7q7kiq) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/test_example_module.py#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Name the file `example_module_test.py` and add a short docstring to the top of the file. Also `pylint` is really not happy.
</blockquote></details>

Also add the copyright and license header.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[drake_cmake_installed/src/simple_bindings/example_module.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-wj3aqqC8lclaQFXV:-L7-wj3aqqC8lclaQFXW:bp10o41) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/example_module.cc#L19)):*
> ```cpp
> class SimpleAdder : public LeafSystem<T> {
>  public:
>   SimpleAdder(T add)
> ```

`explicit`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake_cmake_external/CMakeLists.txt, line 36 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-r33E9lIbfWSwYAVW:-L7R6a23eU1QQ0vpsPRl:b-oujoeu) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_external/CMakeLists.txt#L36)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Remove. Does not add anything and quite possibly confuses things.
</blockquote></details>

I personally found the subproject structure confusing, and had to root around to figure out why we had this way.

Is there a link that I can point to, in this case? Or a better wording?

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 8 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-sDI5SqMMzlhtWAtW:-L7R9bAOyHg8ijY33rD4:b-fmdrh3) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L8)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Remove. You are misunderstanding how `target_link_libraries` works. The name is a legacy and you should never need to use a `pybind11_INCLUDE_DIRS` variable.
</blockquote></details>

Done. Reworded, as it was unexpected to me that `pybind11_add_module` does not correctly include `pybind11`, which is because our `pybind11-config` diverges from the original.

---

*[drake_cmake_installed/src/simple_bindings/example_module.cc, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-wPDNVh-choXVJGiH:-L7R9VE5kCwou7lsKDtL:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/example_module.cc#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Add the copyright and license header.
</blockquote></details>

Done.

---

*[drake_cmake_installed/src/simple_bindings/example_module.cc, line 19 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-wj3aqqC8lclaQFXV:-L7R9Va87zr7cBc27yOS:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/example_module.cc#L19)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`explicit`
</blockquote></details>

Done.

---

*[drake_cmake_installed/CMakeLists.txt, line 46 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-rKwPckWkNHZa1XRq:-L7R9mZUdE9LmYl6CyVj:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/CMakeLists.txt#L46)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

This is exactly why you should not be throwing unnecessary dependencies into `drake-config.cmake`.
</blockquote></details>

Done.

---

*[drake_cmake_installed/src/simple_bindings/test_example_module.py, line 1 at r1](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98#-L7-u9h1vjti_j9P5-Km:-L7R9np5e4BN8sBjJI9A:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/test_example_module.py#L1)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Also add the copyright and license header.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by jamiesnape** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake_cmake_external/CMakeLists.txt, line 36 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-L7-r33E9lIbfWSwYAVW:-LAU90iLBaCp9ZysvIQT:b-buji34) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_external/CMakeLists.txt#L36)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I personally found the subproject structure confusing, and had to root around to figure out why we had this way.

Is there a link that I can point to, in this case? Or a better wording?
</blockquote></details>

I don't think so. The CMake documentation is sufficient and easy to find (if you think it is neither of these, please open an issue upstream and we will try to fix) and we do not annotate every CMake call with a link to its documentation.

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 8 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-L7-sDI5SqMMzlhtWAtW:-LAU8Um0DYCS6w4oy8I7:bag72w9) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L8)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Reworded, as it was unexpected to me that `pybind11_add_module` does not correctly include `pybind11`, which is because our `pybind11-config` diverges from the original.
</blockquote></details>

Even if `cps2cmake` did define `pybind11_INCLUDE_DIRS`, you still would not use it. This is just how you use CMake these days.

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 4 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-LAU9O-6AjAuAHptzhy2:-LAU9O-6AjAuAHptzhy3:bphw28l) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/08e11be7397a8dfa6c9834184bee52a5b45a374c/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L4)):*
> ```CMake
> # vi: set ft=cmake :
> 
> # Copyright (c) 2017, Massachusetts Institute of Technology.
> ```

Probably `Copyright (c) 2018, Toyota Research Institute.` for all the new files?

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 41 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-LAU8fuf92Lbch7ZSac7:-LAU8fuf92Lbch7ZSac8:b-7dfba1) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/08e11be7397a8dfa6c9834184bee52a5b45a374c/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L41)):*
> ```CMake
> target_link_libraries(example_module PUBLIC drake::drake pybind11::module)
> # Revert visibilty preset (workaround for RobotLocomotion/drake#8540).
> set_target_properties(example_module PROPERTIES CXX_VISIBILITY_PRESET "default")
> ```

`Revert visibilty preset set by pybind11_add_module()`? Also quotes are not needed around `default`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by EricCousineau-TRI** [comment]
*[drake_cmake_external/CMakeLists.txt, line 36 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-L7-r33E9lIbfWSwYAVW:-LAUXQPd8ShB03bxaANK:b9qe2t1) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_external/CMakeLists.txt#L36)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

I don't think so. The CMake documentation is sufficient and easy to find (if you think it is neither of these, please open an issue upstream and we will try to fix) and we do not annotate every CMake call with a link to its documentation.
</blockquote></details>

Is there a better way to search for this as a non-expert? What is the best way to find an authoritative source on this exact structure?

My quick searches provide next to nil on finding a *consistent* mention of this; from what I see in the CMake docs for `ExternalProject_Add`, it shows the usage of the method, but does not appear to provide explicit / easily discoverable advice on how to structure your project which shows this structure.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by EricCousineau-TRI** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 8 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-L7-sDI5SqMMzlhtWAtW:-LAU_uMjDG6nutD8vClx:blp1urb) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L8)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Even if `cps2cmake` did define `pybind11_INCLUDE_DIRS`, you still would not use it. This is just how you use CMake these days.
</blockquote></details>

Trying to follow the `pybind11` docs with our setup from `cps2cmake` leads to a whole slew of ugly exceptions:
https://github.com/EricCousineau-TRI/shambhala/commit/8d032c6462e5e318bbb49e6b51433724fd3cdb2e

I can use the interface library setup, but I don't like it as it's more verbose and deviates even further from `pybind11`s usage.
(Will create a Drake issue at some point.)

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 4 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-LAU9O-6AjAuAHptzhy2:-LAUbvTS87_cRxWCGdPa:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/08e11be7397a8dfa6c9834184bee52a5b45a374c/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L4)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Probably `Copyright (c) 2018, Toyota Research Institute.` for all the new files?
</blockquote></details>

Done.

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 41 at r2](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-LAU8fuf92Lbch7ZSac7:-LAUcPmd9KRJcz6_OadD:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/08e11be7397a8dfa6c9834184bee52a5b45a374c/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L41)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

`Revert visibilty preset set by pybind11_add_module()`? Also quotes are not needed around `default`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by jamiesnape** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 8 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-L7-sDI5SqMMzlhtWAtW:-LAUfEE58GsKyFyXy8M8:bj2fwwn) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L8)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Trying to follow the `pybind11` docs with our setup from `cps2cmake` leads to a whole slew of ugly exceptions:
https://github.com/EricCousineau-TRI/shambhala/commit/8d032c6462e5e318bbb49e6b51433724fd3cdb2e

I can use the interface library setup, but I don't like it as it's more verbose and deviates even further from `pybind11`s usage.
(Will create a Drake issue at some point.)
</blockquote></details>

The `pybind11` docs need updating then. They provide exactly the same `INTERFACE` targets.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 8 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-L7-sDI5SqMMzlhtWAtW:-LAUgpKrE-5el7IptV3N:bxstkq3) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L8)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

The `pybind11` docs need updating then. They provide exactly the same `INTERFACE` targets.
</blockquote></details>

Their docs are fine: https://github.com/pybind/pybind11/blob/master/docs/compiling.rst#advanced-interface-library-target

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 8 at r1](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-L7-sDI5SqMMzlhtWAtW:-LAUh0xu2R4MAkCJ0_zX:bk45g85) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L8)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

Their docs are fine: https://github.com/pybind/pybind11/blob/master/docs/compiling.rst#advanced-interface-library-target
</blockquote></details>

What is different?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by EricCousineau-TRI** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake_cmake_installed/src/simple_bindings/CMakeLists.txt, line 8 at r1](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-L7-sDI5SqMMzlhtWAtW:-LDNPSp90HscJNa8JqQk:b-896fix) ([raw file](https://github.com/robotlocomotion/drake-shambhala/blob/a32e7809a81b174072796575276a6ab451701e14/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L8)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

What is different?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-LDNPWrB3Ec6GMy8S_aA:-LDNPWrB3Ec6GMy8S_aB:bzat563) (no related file):*
Getting the following error(s) when building and running off of current `drake@master`:

At one point:

```
4: Failure at /home/eacousineau/proj/tri/repo/branches/drake/master/drake/build_install/include/drake/systems/framework/system_base.h:560 in CreateInputPort(): condition 'port->get_index() 
== this->get_num_input_ports()' failed.
```

After a fresh rebuild:

```
4:     adder = builder.AddSystem(SimpleAdder(100.))
4: RuntimeError: Converting to an int. Type "drake::TypeSafeIndex<drake::systems::InputPortTag>", has an invalid value; it must lie in the range [0, 2³¹ - 1].
```

Seems to be some linking shenanigans?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by EricCousineau-TRI** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/98#-LDNPWrB3Ec6GMy8S_aA:-LDNT_jOBF9bcUDHnDZf:bidk4es) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Getting the following error(s) when building and running off of current `drake@master`:

At one point:

```
4: Failure at /home/eacousineau/proj/tri/repo/branches/drake/master/drake/build_install/include/drake/systems/framework/system_base.h:560 in CreateInputPort(): condition 'port->get_index() 
== this->get_num_input_ports()' failed.
```

After a fresh rebuild:

```
4:     adder = builder.AddSystem(SimpleAdder(100.))
4: RuntimeError: Converting to an int. Type "drake::TypeSafeIndex<drake::systems::InputPortTag>", has an invalid value; it must lie in the range [0, 2³¹ - 1].
```

Seems to be some linking shenanigans?
</blockquote></details>

Confirmed that this does not fail when the same code is run in `drake` Bazel land:
https://github.com/EricCousineau-TRI/drake/commit/8f242cac205d738515e2bc0fb1e671125c04565e

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/drake-shambhala/98)*

**Comment by EricCousineau-TRI** [comment]
May wait until #105 progresses, and then use the same code in this PR.

**Comment by EricCousineau-TRI** [comment]
@RussTedrake Will you need this to be updated for your course this fall?

**Comment by RussTedrake** [comment]
It would be helpful for sure.

**Comment by EricCousineau-TRI** [comment]
Pinging @jamiesnape

**Comment by jamiesnape** [comment]
+@m-chaturvedi is going to look into the outstanding issues.

**Comment by m-chaturvedi** [comment]
:lgtm:

**Pull request merged**
